services:
  # 1. Service de la Base de Données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: handi_db
    restart: always

    # Identifiants: val, val, job_db
    environment:
      POSTGRES_USER: val
      POSTGRES_PASSWORD: val
      POSTGRES_DB: job_db

    # Mappage du port
    ports:
      - "5432:5432"

    # Stockage persistant
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Définition des volumes
volumes:
  postgres_data: